# Generated by Django 4.2.25 on 2025-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finflow', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
    ]
